// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_departures from "./routes/api/departures.ts";
import * as $departures_stop_service_ from "./routes/departures/[stop]/[service].tsx";
import * as $departures_index from "./routes/departures/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $DepartureBoard from "./islands/DepartureBoard.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/departures.ts": $api_departures,
    "./routes/departures/[stop]/[service].tsx": $departures_stop_service_,
    "./routes/departures/index.tsx": $departures_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/DepartureBoard.tsx": $DepartureBoard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
